name: Actions Demo

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3.0.2
      - name: List Files
        run: |
          pwd
          ls -al
      - name: Simple javascript actions
        id: greetings
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Malay"
      - name: Log Time
        run: echo "${{ steps.greetings.outputs.time }}"
