name: Docker Container
on: push

jobs:
  # single container
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.14
    steps:
      - name: Log node version
        run: | 
          node -v
          cat /etc/os-release
  #multiple container
  user-api:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
  #Containers in step
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.14
    steps:
      - name: Log node version
        run: | 
          node -v
          cat /etc/os-release
      - name: Step With Docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: "Hello World!"
      - name: Log node version from container
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: "-v"
