name: Commands Demo

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Echo a string
        run: echo "Hello World"
        continue-on-error: true
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash